from fkt_stonks.fkt_MainWindow.fkt_create_tabs.fkt_PlotTab.StockSelector import StockSelector
from fkt_stonks.fkt_MainWindow.fkt_create_tabs.fkt_PlotTab.DateSelector import DateSelector
from fkt_stonks.fkt_MainWindow.fkt_create_tabs.fkt_PlotTab.CompareSelector import CompareSelector
from fkt_stonks.fkt_MainWindow.fkt_create_tabs.fkt_PlotTab.get_tickers import get_tickers
from fkt_stonks.fkt_MainWindow.fkt_create_tabs.fkt_PlotTab.save_data import save_data